#!/bin/bash

# Installation:
# cd <git-repo>
# curl -O https://raw.githubusercontent.com/codenameyau/dotfiles/master/git-hooks/post-merge--npm && chmod ug+x post-merge--npm && mv post-merge--npm .git/hooks/post-merge

# Description:
# Git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

run_if_updated() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

run_if_updated package.json "npm install && npm prune"
