#!/bin/bash

# Installation:
# curl -O https://raw.githubusercontent.com/codenameyau/dotfiles/master/git/post-commit-dotfiles && chmod ug+x post-commit-dotfiles && mv post-commit-dotfiles .git/hooks/post-commit

# Description:
# Hook to update the dotfiles when changes to this repo are commited.

commited_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

run_if_updated() {
  echo "$commited_files" | grep --quiet "$1" && eval "$2"
}

# TODO: Fix this. It doesn't work and has inverse behavior.
check_if_different() {
  if [ ! cmp --silent "$1" "$2" ]; then
    eval "$3"
  fi
}

echo "Running post-commit hook on dotfiles"

if [ -f ~/.bash_aliases ]; then
  run_if_updated "./shell/.bash_aliases" "~/.bash_aliases" "cp shell/.bash_aliases ~/.bash_aliases"
  echo "[+] Updated ~/.bash_aliases"
fi

if [ -f ~/.gitconfig ]; then
  run_if_updated "shell/.gitconfig" "~/.gitconfig" "cp shell/.gitconfig ~/.gitconfig"
  echo "[+] Updated ~/.gitconfig"
fi

if [ -f ~/.bashrc ]; then
  run_if_updated "shell/.bashrc" "cp shell/.bashrc ~/.bashrc"
  echo "[+] Updated ~/.bashrc"
  source ~/.bashrc
fi

if [ -f ~/.bash_profile ]; then
  run_if_updated "shell/.bash_profile" "cp shell/.bash_profile ~/.bash_profile"
  echo "[+] Updated ~/.bash_profile"
  source ~/.bash_profile
fi

echo # new line
