#!/bin/bash

# Set $numbers to arg 1 or 10 by default.
numbers=${1:-10}

# Grab random numbers and format them with sed substitution.
shuf -i 1000000000-9999999999 -n $numbers | sed 's|\([0-9]\{3\}\)\([0-9]\{3\}\)|(\1) \2-|'
